using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using DataObjects;
using LogicLayer;

namespace Presentation
{
    /// <summary>
    /// Francis Mingomba
    /// Created: 2019/04/09
    /// 
    /// Interaction logic for FrmManageResortProperty.xaml
    /// </summary>
    public partial class FrmManageResortProperty : UserControl
    {
        private Employee _employee;
        private List<ResortProperty> _resortProperties;
        private readonly IResortPropertyManager _resortPropertyManager;
        private readonly IResortPropertyTypeManager _resortPropertyTypeManager;
        private bool _isBtnNewInNewMode;
        private string _errorText = "";

        private int _currentIndex;

        public FrmManageResortProperty()
        {
            InitializeComponent();

            _resortPropertyManager = new ResortPropertyManager();

            _resortPropertyTypeManager = new ResortPropertyTypeManager();
        }

        #region Core Logic

        private void BtnPrevious_OnClick(object sender, RoutedEventArgs e)
        {
            if (_resortProperties != null)
                _currentIndex = (_currentIndex - 1 == -1) ? _resortProperties.Count - 1 : _currentIndex - 1;

            SetFormContext();
        }

        private void BtnNext_OnClick(object sender, RoutedEventArgs e)
        {
            if (_resortProperties != null)
                _currentIndex = (_currentIndex + 1) % _resortProperties.Count;

            SetFormContext();
        }

        private void DtgResortProperties_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            _currentIndex = dtgResortProperties.SelectedIndex;

            SetFormContext();
        }

        private void BtnSave_OnClick(object sender, RoutedEventArgs e)
        {
            bool success = ValidateArgs();

            if (success)
            {
                if (string.IsNullOrEmpty(cmbResortPropertyType.Text))
                    return;

                var resortProperty = new ResortProperty
                {
                    ResortPropertyId = int.Parse(txtResortProperty.Text),
                    ResortPropertyTypeId = cmbResortPropertyType.Text
                };

                if (Save(resortProperty, out string errorStr))
                {
                    MessageBox.Show("Resort Property Saved Successfully");

                    RefreshFormAtCurrentIndex();

                    EnableDirectionNavigation();

                    ToggleNowCancelButtonToNew();
                }
                else
                {
                    MessageBox.Show(
                        $"{((resortProperty.ResortPropertyId == 0) ? "Failed to create resort property" : "Failed to update resort property")}\n{errorStr}");
                }
            }
            else
            {
                MessageBox.Show(_errorText);
            }
        }

        private bool ValidateArgs()
        {
            _errorText = "";


            bool result = true;

            if (string.IsNullOrEmpty(txtResortProperty.Text))
            {
                // auto-correct since resort property is autogenerated
                txtResortProperty.Text = "0";
            }

            if (string.IsNullOrEmpty(cmbResortPropertyType.Text))
            {
                _errorText += "Resort Property Type not set\n";
                result = false;
            }

            return result;
        }

        private void BtnNew_OnClick(object sender, RoutedEventArgs e)
        {
            DisableDirectionNavigation();

            if (!_isBtnNewInNewMode)
            {
                if (_resortProperties != null)
                    _currentIndex = _resortProperties.Count;

                this.resortPropertyForm.DataContext = new ResortProperty();

                ToggleNewButtonToCancel();
            }
            else
            {
                SetupWindow();

                ToggleNowCancelButtonToNew();
            }
        }

        private void TxtFilter_OnTextChanged(object sender, TextChangedEventArgs e)
        {
            string filterTxt = txtFilter.Text.ToLower();

            if (_resortProperties == null)
                return;

            var filteredDtg = _resortProperties.Where(
                x => x.ResortPropertyId.ToString().ToLower().Contains(filterTxt)
                     || x.ResortPropertyTypeId.ToLower().Contains(filterTxt)).ToList();

            dtgResortProperties.ItemsSource = filteredDtg;

            if (filteredDtg.Count != 0)
            {
                _currentIndex = 0;
                SetFormContext();
            }
            else
            {
                this.resortPropertyForm.DataContext = new ResortProperty();
            }
        }

        private void BtnDelete_OnClick(object sender, RoutedEventArgs e)
        {
            var resortProperty = ((FrameworkElement)sender).DataContext as ResortProperty;

            try
            {
                if (resortProperty != null)
                    _resortPropertyManager.DeleteResortProperty(resortProperty.ResortPropertyId, _employee);
                else
                {
                    MessageBox.Show("Unknown Error");
                    return;
                }

                MessageBox.Show("Deleted Successfully");

                SetupWindow();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to delete\n{ex.Message}");
            }
        }

        #endregion

        #region Window Setup

        public void SetupForm(Employee employee)
        {
            _employee = employee;

            SetupWindow();
        }

        private void SetupWindow()
        {
            EnumerateComboBoxes();

            RefreshDataGrid();

            InitializeFormContext();
        }

        private void InitializeFormContext()
        {
            if (_resortProperties?.Count == 0)
                return;

            if (_resortProperties != null)
            {
                _currentIndex = 0;
                SetFormContext();
            }

        }

        private void RefreshDataGrid()
        {
            _resortProperties = GetResortProperties();

            dtgResortProperties.ItemsSource = _resortProperties;
        }

        private void EnumerateComboBoxes()
        {
            List<string> resortPropertyTypesStr = GetResortPropertyTypes().Select(x => x.ResortPropertyTypeId).ToList();

            cmbResortPropertyType.Items.Clear();

            foreach (var element in resortPropertyTypesStr)
                cmbResortPropertyType.Items.Add(element);
        }

        #endregion

        #region External Resource Facing Functions

        private List<ResortProperty> GetResortProperties()
        {
            List<ResortProperty> resortProperties = null;

            try
            {
                resortProperties = _resortPropertyManager.RetrieveResortProperties().ToList();
            }
            catch (Exception e)
            {
                MessageBox.Show($"Failed to retrieve resort properties\n {e.Message}");
            }

            return resortProperties.Count == 0 ? null : resortProperties;
        }

        private List<ResortPropertyType> GetResortPropertyTypes()
        {
            List<ResortPropertyType> resortPropertyTypes = null;

            try
            {
                resortPropertyTypes = _resortPropertyTypeManager.RetrieveResortPropertyTypes().ToList();
            }
            catch (Exception e)
            {
                MessageBox.Show($"Failed to retrieve resort property types\n {e.Message}");
            }

            return resortPropertyTypes;
        }

        private bool Save(ResortProperty resortProperty, out string errorStr)
        {
            try
            {
                errorStr = "";

                if (resortProperty.ResortPropertyId == 0)
                    _resortPropertyManager.AddResortProperty(resortProperty);
                else
                    _resortPropertyManager.UpdateResortProperty(_resortProperties[_currentIndex], resortProperty);

                return true;
            }
            catch (Exception e)
            {
                errorStr = $"{e.Message}\n{e.StackTrace}";
            }

            return false;
        }

        #endregion

        #region Helpers

        private void SetFormContext()
        {
            if (_resortProperties != null)
            {
                var decoupler = _resortProperties[_currentIndex].DeepClone();

                this.resortPropertyForm.DataContext = decoupler;
            }

            HighlightRow();
        }

        private void EnableDirectionNavigation()
        {
            btnNext.IsEnabled = true;
            btnPrevious.IsEnabled = true;
        }

        private void DisableDirectionNavigation()
        {
            btnNext.IsEnabled = false;
            btnPrevious.IsEnabled = false;
        }

        private void RefreshFormAtCurrentIndex()
        {
            RefreshDataGrid();

            SetFormContext();
        }

        private void HighlightRow()
        {
            if (_resortProperties != null)
                dtgResortProperties.SelectedItem = _resortProperties[_currentIndex];
        }

        private void ToggleNewButtonToCancel()
        {
            _isBtnNewInNewMode = true;

            btnAdd.Content = "Cancel";
        }

        private void ToggleNowCancelButtonToNew()
        {
            _isBtnNewInNewMode = false;

            btnAdd.Content = "New";
        }
        #endregion


    }
}
